GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Akvaarioblogi",
  "author": "Juulia Ahven",
  "url": "www.blogspot.com/akvblo",
  "likes": 500
}